server:
  port: 8888

spring:
  application:
    name: CodingFly-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 根据注册中心自动默认规则转发
          lower-case-service-id: true # 开启服务注册小写支持

eureka:
  client:
    enabled: true # 是否开启注册
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/


#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
